export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_TEMPORARY_TOKEN = "SET_TEMPORARY_TOKEN";
